apiVersion: apps/v1
kind: Deployment
metadata:
  name: galiaf
  namespace: galiaf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: galiaf
  template:
    metadata:
      labels:
        app: galiaf
    spec:
      containers:
        - name: galiaf
          image: ghcr.io/your-org/galiaf:a
          ports:
            - containerPort: 8080
          env:
            - name: SENTRY_RELEASE
              value: "1.0.4"
