apiVersion: v1
kind: Service
metadata:
  name: galiaf
  namespace: galiaf
spec:
  type: NodePort
  selector:
    app: galiaf
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30080
