name: Build and Push with Sentry

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: iusenkanov/leonardo
      SENTRY_ORG: bckg
      SENTRY_PROJECT: galiaf

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generate debug ID
        id: debug_id
        run: echo "DEBUG_ID=$(uuidgen)" >> $GITHUB_ENV

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Create Sentry debug bundle
        run: |
          mkdir -p sentry-bundle
          sentry-cli debug-files bundle-jvm \
            --output sentry-bundle \
            --debug-id $DEBUG_ID \
            target/classes

      - name: Upload Sentry debug bundle
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          sentry-cli debug-files upload \
            --org $SENTRY_ORG \
            --project $SENTRY_PROJECT \
            --type jvm sentry-bundle

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/leonardo:${{ env.IMAGE_TAG }}
            ghcr.io/${{ github.repository_owner }}/leonardo:latest
          build-args: |
            SENTRY_DEBUG_ID=${{ env.DEBUG_ID }}
