name: Build and Push to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: iusenkanov/galiaf

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set image tag(s)
        run: |
          echo "RELEASE_VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "RELEASE_FULL=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "IMAGE_LATEST=latest" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:$RELEASE_VERSION \
                       -t $REGISTRY/$IMAGE_NAME:$IMAGE_LATEST .

      - name: Push Docker image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:$RELEASE_VERSION
          docker push $REGISTRY/$IMAGE_NAME:$IMAGE_LATEST

      - name: Notify Sentry of Release
        uses: getsentry/action-release@v1
        with:
          environment: dev
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: bckg
          SENTRY_PROJECT: galiaf
          SENTRY_RELEASE: ${{ env.RELEASE_FULL }}